language: node_js
node_js:
  - "14"
install:
  - npm install
env:
  - BASE_URL="/" VUE_APP_LOCAL_URL="https://ha-talk-api.herokuapp.com/"
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: Viaje9/HaTalk
  on:
    branch: main
  